apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa2025-msapp-worker
  namespace: argocd
spec:
  project: ipa2025
  source:
    repoURL: 'https://github.com/IT2166070100/ipa2025-msapp'
    targetRevision: HEAD
    path: worker/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ipa2025
  syncPolicy:
    automated:
      prune: true
      selfHeal: true